common_gen_config:
  logging:
    log_interval: 50
    log_level: INFO
  pretraining:
    ckpt_path:
  enhancement:
    type: all_keywords
    file_path: ~/common-sense-gen/CommonSenseGeneration/data/extracted_sentences_single.json
  training:
    data:
      csv_file_path:
    hparams:
      learning_rate: 2.0e-5
      batch_size: 3
      min_epochs: 1
      max_epochs: 1
  infrastructure:
    gpus: 1
  output:
    model_name: enhanced_allkw
    val_output_name: val_output_enhanced_allkw.txt
    ckpt_path:
  iterations: 5
  rnd_seed: 42
