common_gen_config:
  logging:
    log_interval: 5
    log_level: INFO
  pretraining:
    ckpt_path:
  enhancement:
    type:
    file_path:
  training:
    data:
      csv_file_path:
    hparams:
      learning_rate: 2.0e-5
      batch_size: 3
      min_epochs: 2
      max_epochs: 2
  infrastructure:
    gpus: 0
  output:
    model_name: baseline
    ckpt_path: ./checkpoints/
  iterations: 1
  rnd_seed: 42