log_interval: 50
log_level: INFO
pretrained_ckpt_path:
enh_type:
enh_path:
csv_path:
valid_path: ./data/valid_references.json
learning_rate: 2.0e-5
batch_size: 3
min_epochs: 1
max_epochs: 1
gpus: 1
base_dir:
model_name: baseline
ckpt_path:
iterations: 5
rnd_seed: 42
remove_dev_duplicates: