common_gen_config:
  logging:
    log_interval: 5
    log_level: INFO
  pretraining:
    ckpt_path:
  enhancement:
    type: subgraph
    file_path: ./data/conceptnet_subgraphs.json
  training:
    data:
      csv_file_path:
    hparams:
      learning_rate: 2.0e-5
      batch_size: 3
      min_epochs: 1
      max_epochs: 1
  infrastructure:
    gpus:
  output:
    model_name: enhanced_subgraph
    ckpt_path:
  iterations: 1
  rnd_seed: 42
