log_interval: 5
log_level: INFO
pretrained_ckpt_path:
enh_type: spantree
enh_path: ./data/conceptnet_spantrees.json
csv_path:
valid_path: ./data/valid_references.json
learning_rate: 2.0e-5
batch_size: 3
min_epochs: 1
max_epochs: 1
gpus:
base_dir:
model_name: enhanced_spantree
ckpt_path:
iterations: 1
rnd_seed: 42
remove_dev_duplicates: yes
