log_interval: 5
log_level: INFO
pretrained_ckpt_path:
enh_type:
enh_path:
dataset_path: ./data/error_fixer_delsubtree.data
csv_path:
valid_path: ./data/valid_references.json
learning_rate: 2.0e-5
batch_size: 3
min_epochs: 2
max_epochs: 2
gpus: 0
base_dir:
model_name: baseline
ckpt_path: ./checkpoints/
iterations: 1
rnd_seed: 42
remove_dev_duplicates: yes
postprocess_type: 
postprocess_model_path:
