# logging
log_interval:
log_level:

# pretraining
pretrained_ckpt_path:

# enhancement
enh_type:
enh_path:

# data
csv_path:
valid_path:

# training:
learning_rate:
batch_size:
min_epochs:
max_epochs:

# environment
gpus:
base_dir:
rnd_seed:

# output
model_name:
ckpt_path:

iterations:
remove_dev_duplicates: