common_gen_config:
  logging:
    log_interval:
    log_level:
  pretraining:
    ckpt_path:
  enhancement:
    type:
    file_path:
  training:
    data:
      csv_file_path:
    hparams:
      learning_rate:
      batch_size:
      min_epochs:
      max_epochs:
  infrastructure:
    gpus:
  output:
    model_name:
    ckpt_path:
  iterations:
  rnd_seed: